language: vim
cache:
  directories:
    - $HOME/.rvm
    - $HOME/.vvm
before_install:
  - curl https://raw.githubusercontent.com/kana/vim-version-manager/master/bin/vvm | python - setup; true
  - source ~/.vvm/etc/login
  - vvm update_itself
  - vvm use vimorg--v7.4.2367 --install --with-features=huge
  -
  - rvm use 2.5.0 --install --binary --fuzzy
script: rake ci
